version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest

commands:
  set_git_user:
    description: "setup circle CI as a git user"
    steps:
      - add_ssh_keys

      - run: |
          git config credential.helper 'cache --timeout=120'
          git config user.name 'CircleCI'
          git config user.email '<>'

  set_production_environment:
    description: "sets up our needed environment variables"
    steps:
      - run: |
          echo NODE_ENV=production > .env

  get_dependencies:
    description: "fetch all necessary dependencies"
    steps:
      - checkout
      - set_production_environment

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: |
          rm -rf .buildfiles
          git clone git@github.com:daniellacosse/typescript-buildfiles.git .buildfiles
          make .make/yarn.lock

      - save_cache:
          paths:
            - .make
            - .buildfiles
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
jobs:
  build:
    executor: node

    steps:
      - get_dependencies

      - run: make artifacts/app/index.html

  lint:
    executor: node

    steps:
      - get_dependencies

      - run: make lint

  test:
    executor: node

    steps:
      - get_dependencies

      - run: make test

  coverage:
    executor: node

    steps:
      - get_dependencies

      - run: make coverage

  # release_patch:
  #   executor: node
  #   steps:
  #     - get_dependencies
  #     - set_git_user
  #     - run: |
  #         set -e
  #         git checkout $CIRCLE_BRANCH
  #         # tag master with new version/docs and push
  #         make release!
  #         git push origin $CIRCLE_BRANCH --tags

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - lint:
          filters:
            branches:
              ignore:
                - master
      - test:
          filters:
            branches:
              ignore:
                - master
      - coverage:
          filters:
            branches:
              ignore:
                - master
  # release:
  #   jobs:
  #     - release_patch:
  #         filters:
  #           branches:
  #             only: master
