version: 2.1

executors:
  node:
    docker:
      - image: circleci/ruby:latest-node

commands:
  set_git_user:
    description: "setup circle CI as a git user"
    steps:
      - add_ssh_keys

      - run: |
          git config credential.helper 'cache --timeout=120'
          git config user.name 'CircleCI'
          git config user.email '<>'

  set_production_environment:
    description: "sets up our needed environment variables"
    steps:
      - run: |
          echo NODE_ENV=production > .env

  get_dependencies:
    description: "fetch all necessary dependencies"
    steps:
      - checkout
      - set_production_environment

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: make .artifacts/yarn.lock

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
jobs:
  checks:
    executor: node

    steps:
      - get_dependencies

      - run: yarn checks

workflows:
  checks:
    jobs:
      - checks:
          filters:
            branches:
              ignore:
                - master
