version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest

commands:
  set_git_user:
    description: "setup circle CI as a git user"
    steps:
      - add_ssh_keys

      - run: |
          git config credential.helper 'cache --timeout=120'
          git config user.name 'CircleCI'
          git config user.email '<>'

  set_production_environment:
    description: "sets up our needed environment variables"
    steps:
      - run: |
          echo NODE_ENV=production > .env

  get_dependencies:
    description: "fetch all necessary dependencies"
    steps:
      - checkout
      - set_production_environment

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: |
          rm -rf .gitmodules && rm -rf .buildfiles
          git submodule add --force git@github.com:daniellacosse/typescript-buildfiles.git .buildfiles
          make .artifacts/yarn.lock

      - save_cache:
          paths:
            - .artifacts
            - .buildfiles
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
jobs:
  check:
    executor: node

    steps:
      - get_dependencies

      - run: make checks

workflows:
  check:
    jobs:
      - check:
          filters:
            branches:
              ignore:
                - master
